### ISSUE TITLE
DB migration runner lock bug

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2077]
```
  | 2023-05-19T13:18:56.366-07:00 | INFO 2023-05-19T20:18:56.365Z Starting Medplum Server...
  | 2023-05-19T13:18:56.366-07:00 | INFO 2023-05-19T20:18:56.366Z configName: aws:/medplum/prod/
  | 2023-05-19T13:19:01.237-07:00 | INFO 2023-05-19T20:19:01.236Z Run database migration v42
  | 2023-05-19T13:19:04.797-07:00 | error: deadlock detected
  | 2023-05-19T13:19:04.797-07:00 | at Parser.parseErrorMessage (/usr/src/medplum/node_modules/pg-protocol/dist/parser.js:287:98)
  | 2023-05-19T13:19:04.797-07:00 | at Parser.handlePacket (/usr/src/medplum/node_modules/pg-protocol/dist/parser.js:126:29)
  | 2023-05-19T13:19:04.797-07:00 | at Parser.parse (/usr/src/medplum/node_modules/pg-protocol/dist/parser.js:39:38)
  | 2023-05-19T13:19:04.797-07:00 | at Socket.<anonymous> (/usr/src/medplum/node_modules/pg-protocol/dist/index.js:11:42)
  | 2023-05-19T13:19:04.797-07:00 | at Socket.emit (node:events:513:28)
  | 2023-05-19T13:19:04.797-07:00 | at addChunk (node:internal/streams/readable:324:12)
  | 2023-05-19T13:19:04.797-07:00 | at readableAddChunk (node:internal/streams/readable:297:9)
  | 2023-05-19T13:19:04.797-07:00 | at Readable.push (node:internal/streams/readable:234:10)
  | 2023-05-19T13:19:04.797-07:00 | at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  | 2023-05-19T13:19:04.797-07:00 | length: 307,
  | 2023-05-19T13:19:04.797-07:00 | severity: 'ERROR',
  | 2023-05-19T13:19:04.797-07:00 | code: '40P01',
  | 2023-05-19T13:19:04.797-07:00 | detail: 'Process 10837 waits for ShareLock on virtual transaction 11/17013777; blocked by process 10838.\n' +
  | 2023-05-19T13:19:04.797-07:00 | 'Process 10838 waits for ExclusiveLock on advisory lock [16400,0,1,1]; blocked by process 10837.',
  | 2023-05-19T13:19:04.797-07:00 | hint: 'See server log for query details.',
  | 2023-05-19T13:19:04.798-07:00 | position: undefined,
  | 2023-05-19T13:19:04.798-07:00 | internalPosition: undefined,
  | 2023-05-19T13:19:04.798-07:00 | internalQuery: undefined,
  | 2023-05-19T13:19:04.798-07:00 | where: undefined,
  | 2023-05-19T13:19:04.798-07:00 | schema: undefined,
  | 2023-05-19T13:19:04.798-07:00 | table: undefined,
  | 2023-05-19T13:19:04.798-07:00 | column: undefined,
  | 2023-05-19T13:19:04.798-07:00 | dataType: undefined,
  | 2023-05-19T13:19:04.798-07:00 | constraint: undefined,
  | 2023-05-19T13:19:04.798-07:00 | file: 'deadlock.c',
  | 2023-05-19T13:19:04.798-07:00 | line: '1146',
  | 2023-05-19T13:19:04.798-07:00 | routine: 'DeadLockReport'
  | 2023-05-19T13:19:04.798-07:00 | }
```

**Comment by codyebberson** [comment]
Cannot repro. More background reading: https://www.cybertec-postgresql.com/en/postgresql-understanding-deadlocks/
