### ISSUE TITLE
npm run dev error from Medplum server (v3.2.11)

### ISSUE THREAD

**Issue by ha-ccoon** [medplum/medplum#5266]
Hi Medplum team,

The below error happened when it starts the server. `npm run dev`

- Error occured from version 3.2.11 (3.2.11, 3.2.12, 3.2.13 all have the same error).
- 3.2.10 works well 

Could you please look into this?

```
> @medplum/server@3.2.13 dev
> ts-node-dev --poll --respawn --transpile-only --require ./src/otel/instrumentation.ts src/index.ts

[INFO] 14:20:46 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.2, typescript ver. 5.6.2)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Volumes/data/dev/lien/fhirbox/medplum-examples/medplum/packages/server/src/fhir/repo.ts:2262:11)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._compile (/Volumes/data/dev/lien/fhirbox/medplum-examples/medplum/node_modules/source-map-support/source-map-support.js:521:25)
    at Module.m._compile (/private/var/folders/qb/fpx4hbcd25936pj8w5ds36t80000gn/T/ts-node-dev-hook-7390350700180615.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/qb/fpx4hbcd25936pj8w5ds36t80000gn/T/ts-node-dev-hook-7390350700180615.js:114:20)
    at require.extensions.<computed> (/private/var/folders/qb/fpx4hbcd25936pj8w5ds36t80000gn/T/ts-node-dev-hook-7390350700180615.js:71:20)
    at Object.nodeDevHook [as .ts] (/Volumes/data/dev/lien/fhirbox/medplum-examples/medplum/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1098:12)
```

**Comment by codyebberson** [comment]
Hi @ha-ccoon -

Have you upgraded the `@medplum/fhir-router` dependency?

I suspect the commit that broke your project is https://github.com/medplum/medplum/pull/4358

In that commit, we changed:

```ts
export class Repository extends BaseRepository implements FhirRepository<PoolClient>, Disposable {
```

to:

```ts
export class Repository extends FhirRepository<PoolClient> implements Disposable {
```

It is a small semantic change, but does require upgrading `@medplum/fhir-router`

**Comment by dooleydiligent** [comment]
A little confused by this.  I have just done `git clone ...` and followed the instructions to `npm run dev` and I get this same error.

How does one upgrade @medplum/fhir-router beyond doing `npm ci` on a fresh clone?

package.json in packages/server reports `"@medplum/fhir-router": : "3.2.16",` which is the latest version.

**Comment by ha-ccoon** [comment]
> @medplum/fhir-router

Hi @codyebberson,

Sorry for the late reply. It works well after upgrading `@medplum/fhir-router`.

Thanks a lot!

**Comment by ha-ccoon** [comment]
> A little confused by this. I have just done `git clone ...` and followed the instructions to `npm run dev` and I get this same error.
> 
> How does one upgrade @medplum/fhir-router beyond doing `npm ci` on a fresh clone?
> 
> package.json in packages/server reports `"@medplum/fhir-router" : "3.2.16",` which is the latest version.

Hi dooley,

Not sure if you have solved the problem, but this is what I have done.

I have upgraded the entire packages with `npm ci` and `npm run build` afterward.

If you want to upgrade just one package, then simply go to that package folder and execute the same code above.
In this case, execute the same code above under packages/fhir-router/.
