### ISSUE TITLE
Non-obvious error from name collision with CloudFront Public Keys

### ISSUE THREAD

**Issue by ianplunkett** [medplum/medplum#5272]
I was following the [AWS set up guide](https://www.medplum.com/docs/self-hosting/install-on-aws) and I used the default "demo" name provided by `medplum aws init`

The initialization completed but in the output I noticed the following. 

```
SIGNING KEY

Medplum uses AWS CloudFront Presigned URLs for binary content such as file uploads.
Error: Unable to create signing key:  The name that you are using to create a CloudFront public key is associated with another public key in your account.
Unable to generate signing key.
Please manually create a signing key and enter the key ID and public key in the config file.
You must set the "signingKeyId", "signingKey", and "signingKeyPassphrase" settings.
```

There was already a CloudFront key associated with "demo".

Subsequently the bootstrap failed since my configuration didn't include a public key details.
```
my-medplum-cdk-config % npx cdk bootstrap -c config=medplum.demo.config.json
[WARNING] aws-cdk-lib.aws_cloudfront_origins.S3Origin is deprecated.
  Use `S3BucketOrigin` or `S3StaticWebsiteOrigin` instead.
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_cloudfront_origins.S3Origin#bind is deprecated.
  Use `S3BucketOrigin` or `S3StaticWebsiteOrigin` instead.
  This API will be removed in the next major release.
Error: Public key must be in PEM format (with the BEGIN/END PUBLIC KEY lines); got undefined
    at new PublicKey (/Users/ianplunkett/Development/medplum/my-medplum-cdk-config/node_modules/aws-cdk-lib/aws-cloudfront/lib/public-key.js:1:1024)
    at new B (/Users/ianplunkett/Development/medplum/my-medplum-cdk-config/node_modules/@medplum/cdk/dist/cjs/index.cjs:4:83541)
    at new re (/Users/ianplunkett/Development/medplum/my-medplum-cdk-config/node_modules/@medplum/cdk/dist/cjs/index.cjs:4:86630)
    at new V (/Users/ianplunkett/Development/medplum/my-medplum-cdk-config/node_modules/@medplum/cdk/dist/cjs/index.cjs:4:86042)
    at /Users/ianplunkett/Development/medplum/my-medplum-cdk-config/node_modules/@medplum/cdk/dist/cjs/index.cjs:4:86973

```

I think either some color coding of the error message or stopping the script, looping on failure or something similar would be beneficial here.  I can imagine others may also run into this issue.

**Comment by Amman30** [comment]
any updates on this?
